### ISSUE TITLE
Solve "Cannot find name '$'" linter error

### ISSUE THREAD

**Issue by caioflores** [hangxingliu/vscode-coding-tracker-server#6]
This error keep showing in linter console.

**Comment by hangxingliu** [comment]
If this error is showing by `Typescript Check` in VS Code.

You can execute this command in project root path: `npm install @types/jquery @types/bootstrap`

Because VSCode would be automatically install types file which you have require it explicitly like: `require('xxx')`. But not include it in HTML, like: `<script src="xxx/jquery.min.js"></script>`

--- 

If this error is showing by other lint tools (like: jshint, jslint, etc...)   
You need query document of lint tool you are using to get the answer about "How to add jquery library in default lint environment".

In this project, I only use ESLint. So I configured ESLint in file `.eslintrc.json`. And I set `jquery` is a default library  in line 7 in this file: <https://github.com/hangxingliu/vscode-coding-tracker-server/blob/master/.eslintrc.json#L8>
